import { Utterance, NoteSection } from "@/types";
import { soapTemplate } from "./seed";

export function parseTranscriptToSections(
  utterances: Utterance[],
  encounterId: string,
  patientName?: string,
  clinicianName?: string,
  dateStr?: string
): NoteSection[] {
  const fullText = utterances.map((u) => u.text).join(" ").toLowerCase();

  return soapTemplate.sections.map((tmpl) => {
    let content = "";

    if (tmpl.id === "identification") {
      const parts: string[] = [];
      if (patientName) parts.push(`Paciente: ${patientName}`);
      if (clinicianName) parts.push(`Médico: ${clinicianName}`);
      if (dateStr) parts.push(`Data: ${dateStr}`);
      content = parts.join("\n") || "(Gerado automaticamente — revise e edite)";
    } else if (tmpl.generationRules) {
      const keywords = tmpl.generationRules.split(",").map((k) => k.trim().toLowerCase());
      const matched = utterances.filter((u) =>
        keywords.some((kw) => u.text.toLowerCase().includes(kw))
      );
      if (matched.length > 0) {
        content = matched.map((u) => `- ${u.text}`).join("\n");
      }
    }

    if (!content) {
      content = "(Gerado automaticamente — revise e edite)";
    }

    return {
      id: `${encounterId}_${tmpl.id}`,
      title: tmpl.title,
      content,
      autoGenerated: true,
    };
  });
}
