export interface Clinic {
  id: string;
  name: string;
  address: string;
}

export interface Clinician {
  id: string;
  name: string;
  specialty: string;
  crm: string;
  cpf?: string;
  email?: string;
  clinicAddress?: string;
  clinics?: Clinic[];
}

export interface TimeBlock {
  id: string;
  date: string;
  startTime: string;
  endTime: string;
  reason: string;
  recurrence: "none" | "daily" | "weekly";
  clinicianId: string;
}

export interface PatientDocument {
  id: string;
  name: string;
  date: string;
  type: "exame" | "laudo" | "imagem" | "outro";
}

export interface BeforeAfterPhoto {
  id: string;
  date: string;
  label: string;
  beforeImage: string; // base64 data URI
  afterImage?: string; // base64 data URI
}

export interface EvolutionPhoto {
  id: string;
  date: string;
  label: string;
  image: string; // base64 data URI
  notes?: string;
  weight?: number; // kg
  encounterId?: string;
}

export interface Patient {
  id: string;
  name: string;
  birthDate?: string;
  sex?: "M" | "F" | "O" | "NA";
  phone?: string;
  email?: string;
  notes?: string;
  archived?: boolean;
  cpf?: string;
  rg?: string;
  addressLine?: string;
  cep?: string;
  children?: string[];
  petName?: string;
  referralSource?: string;
  diagnoses?: string[];
  drugAllergies?: string[];
  documents?: PatientDocument[];
  beforeAfterPhotos?: BeforeAfterPhoto[];
  evolutionPhotos?: EvolutionPhoto[];
}

export type EncounterStatus = "recording" | "draft" | "reviewed" | "final";

export interface Encounter {
  id: string;
  patientId: string;
  clinicianId: string;
  startedAt: string;
  endedAt?: string;
  durationSec: number;
  status: EncounterStatus;
  chiefComplaint?: string;
  location?: string;
  transcriptId?: string;
  noteId?: string;
}

export interface Utterance {
  speaker: "medico" | "paciente";
  text: string;
  tsSec?: number;
}

export interface Transcript {
  id: string;
  encounterId: string;
  source: "pasted" | "mock";
  content: Utterance[];
}

export interface NoteSection {
  id: string;
  title: string;
  content: string;
  autoGenerated: boolean;
  lastEditedAt?: string;
}

export interface Note {
  id: string;
  encounterId: string;
  templateId: string;
  sections: NoteSection[];
}

export interface NoteTemplateSection {
  id: string;
  title: string;
  hint: string;
  generationRules: string;
}

export interface NoteTemplate {
  id: string;
  name: string;
  sections: NoteTemplateSection[];
}

export type ScheduleStatus = "scheduled" | "confirmed" | "in_progress" | "done" | "no_show" | "rescheduled";
export type ScheduleType = "primeira" | "retorno" | "procedimento";

export interface ScheduleEvent {
  id: string;
  date: string; // YYYY-MM-DD
  startTime: string; // HH:MM
  endTime?: string; // HH:MM
  patientId: string;
  clinicianId: string;
  type: ScheduleType;
  status: ScheduleStatus;
  notes?: string;
  encounterId?: string;
}

export interface AppSettings {
  persistLocal: boolean;
  showSimulatedBanner: boolean;
  sessionSimulated: { isLoggedIn: boolean };
}

export interface Prescription {
  id: string;
  type: "simple" | "special";
  content: string;
  medications: Medication[];
  signed: boolean;
  createdAt: string;
  encounterId?: string;
  patientId?: string;
}

export interface Medication {
  id: string;
  commercialName: string;
  activeCompound: string;
  concentration: string;
  presentation: string;
  isCompounded: boolean;
  compoundedFormula: string;
  usageInstructions: string;
}

export interface TranscriptArchive {
  id: string;
  date: string;
  patientName: string;
  patientId: string;
  encounterId?: string;
  content: string;
}

export interface CustomNoteTemplate {
  id: string;
  name: string;
  content: string;
  createdAt: string;
}

export interface MedicationEvent {
  id: string;
  patientId: string;
  medicationName: string;
  date: string;
  status: "prescrito" | "suspenso" | "nao_renovado";
  note?: string;
  encounterId?: string;
}

export interface DocumentCompliance {
  regulatorySource: string;
  requirements: string[];
  warnings: string[];
  needsConfirmation: boolean;
  confirmedByDoctor?: boolean;
  confirmedAt?: string;
}

export interface ClinicalDocument {
  id: string;
  patientId: string;
  encounterId?: string;
  type: "prescricao" | "atestado" | "solicitacao_exames" | "orientacoes" | "outro";
  title?: string;
  content: string;
  createdAt: string;
  signedAt?: string;
  signedBy?: string;
  status: "draft" | "ready_to_sign" | "signed";
  recipeType?: "simples" | "antimicrobiano" | "controle_especial";
  compliance?: DocumentCompliance;
}

export interface AppData {
  clinicians: Clinician[];
  patients: Patient[];
  encounters: Encounter[];
  transcripts: Transcript[];
  notes: Note[];
  scheduleEvents: ScheduleEvent[];
  timeBlocks: TimeBlock[];
  settings: AppSettings;
}
