export interface Clinician {
  id: string;
  name: string;
  specialty: string;
  crm: string;
}

export interface Patient {
  id: string;
  name: string;
  birthDate?: string;
  sex?: "M" | "F" | "O" | "NA";
  phone?: string;
  notes?: string;
  archived?: boolean;
}

export type EncounterStatus = "recording" | "draft" | "reviewed" | "final";

export interface Encounter {
  id: string;
  patientId: string;
  clinicianId: string;
  startedAt: string;
  endedAt?: string;
  durationSec: number;
  status: EncounterStatus;
  chiefComplaint?: string;
  location?: string;
  transcriptId?: string;
  noteId?: string;
}

export interface Utterance {
  speaker: "medico" | "paciente";
  text: string;
  tsSec?: number;
}

export interface Transcript {
  id: string;
  encounterId: string;
  source: "pasted" | "mock";
  content: Utterance[];
}

export interface NoteSection {
  id: string;
  title: string;
  content: string;
  autoGenerated: boolean;
  lastEditedAt?: string;
}

export interface Note {
  id: string;
  encounterId: string;
  templateId: string;
  sections: NoteSection[];
}

export interface NoteTemplateSection {
  id: string;
  title: string;
  hint: string;
  generationRules: string;
}

export interface NoteTemplate {
  id: string;
  name: string;
  sections: NoteTemplateSection[];
}

export interface AppSettings {
  persistLocal: boolean;
  showSimulatedBanner: boolean;
  sessionSimulated: { isLoggedIn: boolean };
}

export interface AppData {
  clinicians: Clinician[];
  patients: Patient[];
  encounters: Encounter[];
  transcripts: Transcript[];
  notes: Note[];
  settings: AppSettings;
}
